[package]
name = "pgarchive"
version = "0.1.0"
edition = "2021"

[lib]
name = "pgarchive"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.30"

[dev-dependencies]
hex-literal = "0.4.1"
